In [6]:
# Import Dependencies
import pandas as pd

In [7]:
# Create a path to the csv and read it into a Pandas DataFrame
csv_path = "Resources/ted_talks.csv"
ted_df = pd.read_csv(csv_path)

ted_df.head()

,comments,description,duration,event,languages,main_speaker,name,title,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,Do schools kill creativity?,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,43,Al Gore,Al Gore: Averting the climate crisis,Averting the climate crisis,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,26,David Pogue,David Pogue: Simplicity sells,Simplicity sells,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,35,Majora Carter,Majora Carter: Greening the ghetto,Greening the ghetto,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,The best stats you've ever seen,12005869

In [10]:
# Figure out the minimum and maximum views for a TED Talk
min = ted_df["views"].min()
print(min)
ted_df["views"].max()

50443

47227110

In [11]:
# Create bins in which to place values based upon TED Talk views
bins = [0,199000,399000,599000,799000,999000,1999000,3999000,5999000,7999000,500000000]

# Create labels for these bins
group_labels = ["A","B","C","D","E","F","G","H","I","J"]

In [13]:
# Slice the data and place it into bins
ted_df["View Group"] = pd.cut(ted_df["views"], bins, labels=group_labels)
ted_df.head(10)

,comments,description,duration,event,languages,main_speaker,name,title,views,View Group
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,Do schools kill creativity?,47227110,J
1,265,With the same humor and humanity he exuded in ...,977,TED2006,43,Al Gore,Al Gore: Averting the climate crisis,Averting the climate crisis,3200520,G
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,26,David Pogue,David Pogue: Simplicity sells,Simplicity sells,1636292,F
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,35,Majora Carter,Majora Carter: Greening the ghetto,Greening the ghetto,1697550,F
4,593,You've never seen data presented like this. Wi...,1190,TED2006,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,The best stats you've ever seen,12005869,J
5,672,"Tony Robbins discusses the ""invisible forces"" ...",1305,TED2006,36,Tony Robbins,Tony Robbins: Why we do what we do,Why we do what we do,20685401,J
6,919,When two young Mormon missionaries knock on Ju...,992,TED2006,31,Julia Sweeney,Julia Sweeney: Letting go of God,Letting go of God,3769987,G
7,46,Architect Joshua Prince-Ramus takes the audien...,1198,TED2006,19,Joshua Prince-Ramus,Joshua Prince-Ramus: Behind the design of Seat...,Behind the design of Seattle's library,967741,E
8,852,Philosopher Dan Dennett calls for religion -- ...,1485,TED2006,32,Dan Dennett,Dan Dennett: Let's teach religion -- all relig...,Let's teach religion -- all religion -- in sch...,2567958,G
9,900,"Pastor Rick Warren, author of ""The Purpose-Dri...",1262,TED2006,31,Rick Warren,Rick Warren: A life of purpose,A life of purpose,3095993,G

In [ ]:
# Place the data series into a new column inside of the DataFrame

In [ ]:
# Create a GroupBy object based upon "View Group"


# Find how many rows fall into each bin


# Get the average of each column within the GroupBy object